### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/go-web-examples#1]
- [x] #2 | [Wiki page](https://github.com/hcltech84/go-web-examples/wiki/01-%E2%80%90-Create-a-basic-http-server)
- [x] #3 
- [x] MySQL, template, forms: see <https://github.com/hcltech84/gowiki>
- [ ] Assets and files
- [ ] Middleware basic
- [ ] Middleware advanced
- [ ] Sessions
- [ ] JSON
- [ ] Websockets
- [ ] Password hashing
